databases:
  - name: whenarewefree
    databaseName: whenarewefree
    user: whenarewefree

services:
  - type: web
    name: whenarewefree
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: whenarewefree
          property: connectionString
      - key: 9999c3489d33223f1b7ffd3041953bdb
        sync: true
